apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - min:
        cpu: "10m"
        memory: "20Mi"
      max:
        cpu: "100m"
        memory: "200Mi"
      default:
        cpu: "75m"
        memory: "150Mi"
      defaultRequest:
        cpu: "50m"
        memory: "100Mi"
      type: Container